name: Android CI

on:
  push:
    branches: [ master ]
  pull_request:
    types: [opened, synchronize]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: 11
          distribution: zulu

      - name: Make Gradle executable
        run: chmod +x ./gradlew

      - uses: finnp/create-file-action@master
        env:
          FILE_NAME: "local.properties"

      - name: Build with Gradle
        run: ./gradlew build

      - name: Build Debug APK
        run: ./gradlew assembleDebug

  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: 11
          distribution: zulu

      - name: Make Gradle executable
        run: chmod +x ./gradlew

      - uses: finnp/create-file-action@master
        env:
          FILE_NAME: "local.properties"

      - name: lint
        run: ./gradlew lint

      - uses: actions/upload-artifact@v2
        with:
          name: android-lint-report
          path: ~/app/build/reports/lint-results.html

      - uses: actions/upload-artifact@v2
        with:
          name: android-lint-report
          path: ./**/build/reports/lint-results.xml

  detekt:
    continue-on-error: true
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: 11
          distribution: zulu

      - name: Make Gradle executable
        run: chmod +x ./gradlew

      - uses: finnp/create-file-action@master
        env:
          FILE_NAME: "local.properties"

      - name: detekt
        run: ./gradlew detekt

      - uses: actions/upload-artifact@v2
        with:
          name: detekt-report
          path: ./**/build/reports/detekt/detekt.*
  ktlint:
    continue-on-error: true
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: 11
          distribution: zulu

      - name: Make Gradle executable
        run: chmod +x ./gradlew

      - uses: finnp/create-file-action@master
        env:
          FILE_NAME: "local.properties"

      - name: ktlint
        run: ./gradlew ktlintCheck

      - uses: actions/upload-artifact@v2
        with:
          name: ktlint-report
          path: ./**/build/reports/ktlint/